# Generated by Django 5.1.3 on 2024-12-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0002_alter_new_options_new_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='foto',
            field=models.ImageField(null=True, upload_to='static/imags', verbose_name='Картинка'),
        ),
    ]
