# Generated by Django 5.1.3 on 2024-12-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0003_alter_new_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='foto',
            field=models.ImageField(null=True, upload_to='main1/static/imags', verbose_name='Картинка'),
        ),
    ]
