# Generated by Django 5.1.3 on 2024-12-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    

    dependencies = [
        ('main1', '0004_alter_new_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название игры')),
                ('foto', models.ImageField(null=True, upload_to='main1/static/imags', verbose_name='Картинка')),
                ('full_text', models.CharField(max_length=40, verbose_name='Небольшое описание')),
                ('date', models.DateTimeField(verbose_name='Дата анонса')),
            ],
            options={
                'verbose_name': 'Новинки',
                'verbose_name_plural': 'Новинки',
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название игры')),
                ('foto', models.ImageField(null=True, upload_to='main1/static/imags', verbose_name='Картинка')),
                ('full_text', models.CharField(max_length=40, verbose_name='Небольшое описание')),
                ('rating', models.FloatField(verbose_name='Оценка до 2 знаков после запятой')),
            ],
            options={
                'verbose_name': 'Рейтинги',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название игры')),
                ('foto', models.ImageField(null=True, upload_to='main1/static/imags', verbose_name='Картинка')),
                ('full_text', models.TextField(verbose_name='Описание')),
                ('link', models.TextField(verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Обзор',
                'verbose_name_plural': 'Обзоры',
            },
        ),
    ]
