# Generated by Django 5.1.3 on 2024-12-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0005_new_game_ratings_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='foto',
            field=models.ImageField(null=True, upload_to='main1/static/main1/imags', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='new_game',
            name='foto',
            field=models.ImageField(null=True, upload_to='main1/static/main1/imags', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='foto',
            field=models.ImageField(null=True, upload_to='main1/static/main1/imags', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='foto',
            field=models.ImageField(null=True, upload_to='main1/static/main1/imags', verbose_name='Картинка'),
        ),
    ]
