# Generated by Django 5.1.3 on 2024-12-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0007_alter_new_foto_alter_new_game_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='foto',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Картинка'),
        ),
    ]
